/**
 * Rails design rationale: `resources` / `resource` are the heart of Rails'
 * RESTful routing. Each macro expands to up to seven named routes covering
 * the full CRUD lifecycle. This file ports the recognition-only subset of
 * Rails' `ResourcesTest` (controller/resources_test.rb) — the parts that can
 * be verified with `assertRecognizes` alone, without URL-helper generation
 * (which requires a live controller instance wired to `@routes.url_helpers`).
 *
 * Pending gaps:
 * - Tests relying on `assertSimplyRestfulFor`/`assertRestfulNamedRoutesFor`
 *   (named-route URL generation) are deferred until integration-session
 *   cloning is ported (#T-AC14).
 * - Format-extension routes (`/products.xml`, `/products/:id.xml`) are not
 *   yet generated by the mapper (`(\.:format)` suffix is display-only).
 * - The mapper does not yet raise `ArgumentError` for invalid `only`/`except`
 *   values.
 */

import { describe, expect, it } from "vitest";
import { RouteSet } from "../../action-dispatch/routing/route-set.js";
import {
  assertRecognizes,
  assertRouting,
  type RoutingAssertionsHost,
} from "../../action-dispatch/testing/assertions/routing.js";

type Options = Record<string, unknown>;

function assertNotRecognizes(host: RoutingAssertionsHost, options: Options, path: Options): void {
  expect(() =>
    assertRecognizes.call(host, options, path as unknown as Parameters<typeof assertRecognizes>[1]),
  ).toThrow();
}

function assertWhetherAllowed(
  host: RoutingAssertionsHost,
  allowed: string | string[],
  notAllowed: string | string[],
  options: Options,
  action: string,
  path: string,
  method: string,
): void {
  const opts = { ...options, action };
  const pathOpts = { path, method };
  if (([] as string[]).concat(allowed).includes(action)) {
    assertRecognizes.call(host, opts, pathOpts);
  } else if (([] as string[]).concat(notAllowed).includes(action)) {
    assertNotRecognizes(host, opts, pathOpts);
  } else {
    throw new Error(`Invalid action passed: ${action}`);
  }
}

function assertResourceAllowedRoutes(
  host: RoutingAssertionsHost,
  controller: string,
  options: Options,
  shallowOptions: Options,
  allowed: string | string[],
  notAllowed: string | string[],
  path = controller,
): void {
  const shallowPath = `${path}/${shallowOptions["id"]}`;
  const opts = { ...options, controller };
  const shallowOpts = { ...shallowOptions, ...opts };

  assertWhetherAllowed(host, allowed, notAllowed, opts, "index", `${path}`, "get");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "new", `${path}/new`, "get");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "create", `${path}`, "post");
  assertWhetherAllowed(host, allowed, notAllowed, shallowOpts, "show", `${shallowPath}`, "get");
  assertWhetherAllowed(
    host,
    allowed,
    notAllowed,
    shallowOpts,
    "edit",
    `${shallowPath}/edit`,
    "get",
  );
  assertWhetherAllowed(host, allowed, notAllowed, shallowOpts, "update", `${shallowPath}`, "put");
  assertWhetherAllowed(
    host,
    allowed,
    notAllowed,
    shallowOpts,
    "destroy",
    `${shallowPath}`,
    "delete",
  );
}

function assertSingletonResourceAllowedRoutes(
  host: RoutingAssertionsHost,
  controller: string,
  options: Options,
  allowed: string | string[],
  notAllowed: string | string[],
  path = controller.replace(/s$/, ""),
): void {
  const opts = { ...options, controller };

  assertWhetherAllowed(host, allowed, notAllowed, opts, "new", `${path}/new`, "get");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "create", `${path}`, "post");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "show", `${path}`, "get");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "edit", `${path}/edit`, "get");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "update", `${path}`, "put");
  assertWhetherAllowed(host, allowed, notAllowed, opts, "destroy", `${path}`, "delete");
}

function makeHost(): RoutingAssertionsHost {
  return { routes: new RouteSet() };
}

describe("ResourcesTest", () => {
  it("test_irregular_id_with_no_constraints_should_raise_error", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resources("messages"));
    expect(() =>
      assertRecognizes.call(
        host,
        { controller: "messages", action: "show", id: "1.1.1" },
        { path: "messages/1.1.1", method: "get" },
      ),
    ).toThrow();
  });

  it("test_irregular_id_with_constraints_should_pass", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.resources("messages", { constraints: { id: /[0-9]\.[0-9]\.[0-9]/ } }),
    );
    assertRecognizes.call(
      host,
      { controller: "messages", action: "show", id: "1.1.1" },
      { path: "messages/1.1.1", method: "get" },
    );
  });

  it.skip("test_irregular_id_constraints_should_get_passed_to_member_actions — pending: id constraint not propagated to member action routes", () => {});

  it("test_default_singleton_restful_route_uses_get", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resource("product"));
    assertRouting.call(host, "/product", { controller: "products", action: "show" });
  });

  it("test_assert_routing_accepts_all_as_a_valid_method", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.match("/products", { to: "products#show", via: "all" }));
    assertRouting.call(
      host,
      { path: "/products", method: "all" },
      { controller: "products", action: "show" },
    );
  });

  it("test_assert_routing_fails_when_not_all_http_methods_are_recognized", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.match("/products", { to: "products#show", via: ["get", "post", "put"] }),
    );
    expect(() =>
      assertRouting.call(
        host,
        { path: "/products", method: "all" },
        { controller: "products", action: "show" },
      ),
    ).toThrow();
  });

  it.skip("test_invalid_only_option_for_resources — pending: mapper does not raise ArgumentError for invalid only/except", () => {});

  it.skip("test_invalid_only_option_for_singleton_resource — pending: mapper does not raise ArgumentError for invalid only/except", () => {});

  it.skip("test_invalid_except_option_for_resources — pending: mapper does not raise ArgumentError for invalid only/except", () => {});

  it.skip("test_invalid_except_option_for_singleton_resource — pending: mapper does not raise ArgumentError for invalid only/except", () => {});

  it("test_resource_has_only_show_action", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resources("products", { only: "show" }));
    assertResourceAllowedRoutes(host, "products", {}, { id: "1" }, "show", [
      "index",
      "new",
      "create",
      "edit",
      "update",
      "destroy",
    ]);
  });

  it("test_resource_has_only_show_action_with_string_value", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resources("products", { only: "show" }));
    assertResourceAllowedRoutes(host, "products", {}, { id: "1" }, "show", [
      "index",
      "new",
      "create",
      "edit",
      "update",
      "destroy",
    ]);
  });

  it("test_singleton_resource_has_only_show_action", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resource("account", { only: "show" }));
    assertSingletonResourceAllowedRoutes(host, "accounts", {}, "show", [
      "new",
      "create",
      "edit",
      "update",
      "destroy",
    ]);
  });

  it("test_singleton_resource_has_only_show_action_with_string_value", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resource("account", { only: "show" }));
    assertSingletonResourceAllowedRoutes(host, "accounts", {}, "show", [
      "new",
      "create",
      "edit",
      "update",
      "destroy",
    ]);
  });

  it("test_resource_does_not_have_destroy_action", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resources("products", { except: "destroy" }));
    assertResourceAllowedRoutes(
      host,
      "products",
      {},
      { id: "1" },
      ["index", "new", "create", "show", "edit", "update"],
      "destroy",
    );
  });

  it("test_singleton_resource_does_not_have_destroy_action", () => {
    const host = makeHost();
    host.routes!.draw((m) => m.resource("account", { except: "destroy" }));
    assertSingletonResourceAllowedRoutes(
      host,
      "accounts",
      {},
      ["new", "create", "show", "edit", "update"],
      "destroy",
    );
  });

  it.skip("test_resource_has_show_action_but_does_not_have_destroy_action — pending: only+except combined not applied (only wins, except ignored)", () => {});

  it.skip("test_singleton_resource_has_show_action_but_does_not_have_destroy_action — pending: only+except combined not applied (only wins, except ignored)", () => {});

  it.skip("test_resource_has_only_create_action_and_named_route — pending: collection named route not registered when index action is excluded", () => {});

  it.skip("test_resource_has_only_update_action_and_named_route — pending: member named route not registered when show action is excluded", () => {});

  it.skip("test_resource_has_only_destroy_action_and_named_route — pending: member named route not registered when show action is excluded", () => {});

  it.skip("test_singleton_resource_has_only_create_action_and_named_route — pending: singleton named route not registered when show action is excluded", () => {});

  it.skip("test_singleton_resource_has_only_update_action_and_named_route — pending: singleton named route not registered when show action is excluded", () => {});

  it.skip("test_singleton_resource_has_only_destroy_action_and_named_route — pending: singleton named route not registered when show action is excluded", () => {});

  it.skip("test_resource_has_only_collection_action — pending: collection/member extra routes don't inherit controller from resources scope", () => {});

  it.skip("test_resource_has_only_member_action — pending: collection/member extra routes don't inherit controller from resources scope", () => {});

  it.skip("test_singleton_resource_has_only_member_action — pending: collection/member extra routes don't inherit controller from resources scope", () => {});

  it.skip("test_nested_resource_has_only_show_and_member_action — pending: collection/member extra routes don't inherit controller from resources scope", () => {});

  it("test_nested_resource_does_not_inherit_only_option", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.resources("products", { only: "show" }, (r) =>
        r.resources("images", { except: "destroy" }),
      ),
    );
    assertResourceAllowedRoutes(
      host,
      "images",
      { product_id: "1" },
      { id: "2" },
      ["index", "new", "create", "show", "edit", "update"],
      "destroy",
      "products/1/images",
    );
  });

  it("test_nested_resource_does_not_inherit_only_option_by_default", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.resources("products", { only: "show" }, (r) => r.resources("images")),
    );
    assertResourceAllowedRoutes(
      host,
      "images",
      { product_id: "1" },
      { id: "2" },
      ["index", "new", "create", "show", "edit", "update", "destroy"],
      [],
      "products/1/images",
    );
  });

  it("test_nested_resource_does_not_inherit_except_option", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.resources("products", { except: "show" }, (r) =>
        r.resources("images", { only: "destroy" }),
      ),
    );
    assertResourceAllowedRoutes(
      host,
      "images",
      { product_id: "1" },
      { id: "2" },
      "destroy",
      ["index", "new", "create", "show", "edit", "update"],
      "products/1/images",
    );
  });

  it("test_nested_resource_does_not_inherit_except_option_by_default", () => {
    const host = makeHost();
    host.routes!.draw((m) =>
      m.resources("products", { except: "show" }, (r) => r.resources("images")),
    );
    assertResourceAllowedRoutes(
      host,
      "images",
      { product_id: "1" },
      { id: "2" },
      ["index", "new", "create", "show", "edit", "update", "destroy"],
      [],
      "products/1/images",
    );
  });
});
