/**
 * Multiparameter attribute assignment.
 *
 * Mirrors: ActiveRecord::AttributeAssignment (the multiparameter portion)
 *
 * Rails web forms send date/time fields as multiple numbered parameters:
 *   "written_on(1i)" => "2004", "written_on(2i)" => "6", "written_on(3i)" => "24"
 * These are grouped by attribute name and assembled into the appropriate type.
 *
 * Rails source: activerecord/lib/active_record/attribute_assignment.rb
 */

import { AttributeAssignmentError, MultiparameterAssignmentErrors } from "./errors.js";
import { reflectOnAggregation } from "./reflection.js";

const MULTIPARAMETER_ATTRIBUTE_PATTERN = /^([^(]+)\((\d+)([if]?)\)$/;

export function hasMultiparameterKeys(attrs: Record<string, unknown>): boolean {
  return Object.keys(attrs).some((k) => MULTIPARAMETER_ATTRIBUTE_PATTERN.test(k));
}

/**
 * Separate a flat attribute hash into multiparameter groups and regular keys.
 * Mirrors Rails' extract_callstack_for_multiparameter_attributes.
 */
export function extractMultiparameterCallstack(attrs: Record<string, unknown>): {
  multiparams: Record<string, Record<number, unknown>>;
  regular: Record<string, unknown>;
} {
  const multiparams: Record<string, Record<number, unknown>> = {};
  const regular: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(attrs)) {
    const match = key.match(MULTIPARAMETER_ATTRIBUTE_PATTERN);
    if (match) {
      const name = match[1];
      const pos = parseInt(match[2], 10);
      const typeFlag = match[3];
      let castValue: unknown;
      if (typeFlag === "i") {
        castValue = isBlank(value) ? null : parseInt(String(value), 10);
      } else if (typeFlag === "f") {
        castValue = isBlank(value) ? null : parseFloat(String(value));
      } else {
        castValue = isBlank(value) ? null : value;
      }
      (multiparams[name] ??= {})[pos] = castValue;
    } else {
      regular[key] = value;
    }
  }

  return { multiparams, regular };
}

/**
 * Assemble and assign multiparameter groups on an instance.
 * Mirrors Rails' execute_callstack_for_multiparameter_attributes.
 */
export function executeMultiparameterAssignment(
  instance: { constructor: any; writeAttribute(name: string, value: unknown): void },
  callstack: Record<string, Record<number, unknown>>,
): void {
  const errors: Error[] = [];
  const modelClass = instance.constructor;

  for (const [name, partsMap] of Object.entries(callstack)) {
    try {
      const aggregation = reflectOnAggregation(modelClass, name);
      if (aggregation) {
        assignAggregation(instance as any, name, partsMap, aggregation);
      } else {
        assignDateTimeAttribute(instance, name, partsMap, modelClass);
      }
    } catch (e) {
      errors.push(
        new AttributeAssignmentError(
          `error on assignment of multiparameter attributes for column ${name}`,
          e instanceof Error ? e : undefined,
          name,
        ),
      );
    }
  }

  if (errors.length > 0) {
    throw new MultiparameterAssignmentErrors(errors);
  }
}

function assignAggregation(
  instance: Record<string, unknown> & { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
  aggregation: { klass: any },
): void {
  const maxPos = Math.max(...Object.keys(partsMap).map(Number));
  const values = Array.from({ length: maxPos }, (_, i) => partsMap[i + 1] ?? null);

  if (values.every(isBlank)) return;

  const AggClass = aggregation.klass as new (...args: unknown[]) => unknown;
  // Use the property setter generated by composedOf (writes mapped columns + cache).
  instance[name] = new AggClass(...values);
}

function assignDateTimeAttribute(
  instance: { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
  modelClass: any,
): void {
  const colType = modelClass.typeForAttribute?.(name);
  const typeName: string = colType?.type?.() ?? "";

  let maxPos: number;
  if (typeName === "date") {
    maxPos = 3;
  } else if (typeName === "datetime" || typeName === "timestamp" || typeName === "time") {
    maxPos = 6;
  } else {
    maxPos = Math.max(...Object.keys(partsMap).map(Number));
  }

  const values = Array.from({ length: maxPos }, (_, i) => partsMap[i + 1] ?? null);

  if (values.every(isBlank)) {
    instance.writeAttribute(name, null);
    return;
  }

  const assembled = assembleValue(values, typeName);
  instance.writeAttribute(name, assembled);
}

function assembleValue(parts: unknown[], typeName: string): unknown {
  const str = (v: unknown): string | null =>
    v === null || v === undefined || String(v).trim() === "" ? null : String(v).trim();

  if (typeName === "date") {
    const [y, m, d] = parts.map(str);
    if (!y || !m || !d) return null;
    const year = parseInt(y, 10),
      month = parseInt(m, 10),
      day = parseInt(d, 10);
    if (isNaN(year) || isNaN(month) || isNaN(day)) return null;
    // Use local-time Date constructor to avoid UTC-midnight parse issues
    // (ISO string "YYYY-MM-DD" parses as UTC, causing off-by-one in non-UTC zones).
    const date = new Date(year, month - 1, day);
    date.setFullYear(year); // preserve 2-digit years like 0001
    return date;
  }

  if (typeName === "datetime" || typeName === "timestamp") {
    const [y, mo, d, h, mi, s] = parts.map(str);
    if (!y && !mo && !d) return null;
    const year = parseInt(y ?? "0", 10),
      month = parseInt(mo ?? "1", 10),
      day = parseInt(d ?? "1", 10),
      hour = parseInt(h ?? "0", 10) || 0,
      min = parseInt(mi ?? "0", 10) || 0,
      sec = parseInt(s ?? "0", 10) || 0;
    if (isNaN(year) || isNaN(month) || isNaN(day)) return null;
    return new Date(year, month - 1, day, hour, min, sec);
  }

  if (typeName === "time") {
    const [y, mo, d, h, mi, s] = parts.map(str);
    const hour = parseInt(h ?? "0", 10) || 0,
      min = parseInt(mi ?? "0", 10) || 0,
      sec = parseInt(s ?? "0", 10) || 0;
    if (y && mo && d) {
      const year = parseInt(y, 10),
        month = parseInt(mo, 10),
        day = parseInt(d, 10);
      if (isNaN(year) || isNaN(month) || isNaN(day)) return null;
      return new Date(year, month - 1, day, hour, min, sec);
    }
    // Only time parts: use dummy date 2000-01-01 (Rails convention)
    return new Date(2000, 0, 1, hour, min, sec);
  }

  // Generic: return the first non-blank value
  return parts.find((v) => !isBlank(v)) ?? null;
}

function isBlank(v: unknown): boolean {
  if (v === null || v === undefined) return true;
  if (typeof v === "string") return v.trim() === "";
  if (typeof v === "number") return isNaN(v);
  return false;
}
