#!/usr/bin/env -S node --experimental-strip-types
// trails-side CLI for the sibling blazetrailsdev/rfcs repo.
//
// All state lives in $RFCS_DIR (default ~/github/blazetrailsdev/rfcs).
// Mutations go through `git pull --rebase` → frontmatter sed → `git
// commit` → synchronous `git push`. Non-fast-forward push on `claim` is
// the lost-race signal; the caller retries with `next-bundle`.
//
// Read paths consume $RFCS_DIR/index.json, regenerated by the rfcs
// repo's pre-commit hook. If the file is missing or stale (mtime older
// than any story), this script invokes the rfcs-side build-index.mjs
// as a fallback.
import { execSync } from "node:child_process";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const RFCS_DIR = process.env.RFCS_DIR ?? join(homedir(), "github", "blazetrailsdev", "rfcs");

type StoryStatus = "draft" | "ready" | "claimed" | "in-progress" | "done" | "blocked";
type RfcStatus = "draft" | "active" | "closed" | "postponed" | "superseded";

interface RfcEntry {
  id: string;
  title: string | null;
  status: RfcStatus | null;
  owner: string | null;
  packages: string[];
  clusters: string[];
  file_path: string;
}
interface StoryEntry {
  id: string;
  rfc: string;
  title: string | null;
  status: StoryStatus | null;
  cluster: string | null;
  deps: string[];
  deps_rfc: string[];
  est_loc: number | null;
  pr: number | null;
  claim: string | null;
  assignee: string | null;
  blocked_by: string | null;
  file_path: string;
}
interface Index {
  generated_at: string;
  rfcs: RfcEntry[];
  stories: StoryEntry[];
}

function loadIndex(): Index {
  const indexPath = join(RFCS_DIR, "index.json");
  if (!existsSync(indexPath)) {
    rebuildIndex();
  } else {
    const indexMtime = statSync(indexPath).mtimeMs;
    const newer = execSync(
      `find ${JSON.stringify(RFCS_DIR)} -path '*/stories/*.md' -newer ${JSON.stringify(indexPath)} -print -quit`,
      { encoding: "utf8" },
    ).trim();
    if (newer) rebuildIndex();
  }
  return JSON.parse(readFileSync(indexPath, "utf8")) as Index;
}

function rebuildIndex(): void {
  execSync("node scripts/build-index.mjs", { cwd: RFCS_DIR, stdio: "inherit" });
}

function ready(index: Index, opts: { rfc?: string }): StoryEntry[] {
  const rfcStatus = new Map(index.rfcs.map((r) => [r.id, r.status]));
  const storyStatus = new Map(index.stories.map((s) => [s.id, s.status]));
  return index.stories.filter((s) => {
    if (s.status !== "ready") return false;
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (s.deps.some((d) => storyStatus.get(d) !== "done")) return false;
    if (s.deps_rfc.some((d) => rfcStatus.get(d) !== "closed")) return false;
    return true;
  });
}

function nextBundle(
  index: Index,
  opts: { maxLoc: number; cluster?: string; rfc?: string },
): StoryEntry[] {
  const candidates = ready(index, { rfc: opts.rfc })
    .filter((s) => s.est_loc !== null)
    .filter((s) => (opts.cluster ? s.cluster === opts.cluster : true))
    .sort((a, b) => (b.est_loc ?? 0) - (a.est_loc ?? 0));
  const byCluster = new Map<string, StoryEntry[]>();
  for (const s of candidates) {
    const k = s.cluster ?? "_none";
    (byCluster.get(k) ?? byCluster.set(k, []).get(k)!).push(s);
  }
  let best: StoryEntry[] = [];
  for (const group of byCluster.values()) {
    const chosen: StoryEntry[] = [];
    let total = 0;
    for (const s of group) {
      const cost = s.est_loc ?? 0;
      if (total + cost <= opts.maxLoc) {
        chosen.push(s);
        total += cost;
      }
    }
    if (
      chosen.reduce((a, b) => a + (b.est_loc ?? 0), 0) >
      best.reduce((a, b) => a + (b.est_loc ?? 0), 0)
    ) {
      best = chosen;
    }
  }
  return best;
}

function listFiltered(
  index: Index,
  opts: { rfc?: string; status?: string; cluster?: string },
): StoryEntry[] {
  return index.stories.filter((s) => {
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (opts.status && s.status !== opts.status) return false;
    if (opts.cluster && s.cluster !== opts.cluster) return false;
    return true;
  });
}

function statusCounts(index: Index): void {
  const all: StoryStatus[] = ["draft", "ready", "claimed", "in-progress", "done", "blocked"];
  const byRfc = new Map<string, Record<string, number>>();
  for (const s of index.stories) {
    const row = byRfc.get(s.rfc) ?? Object.fromEntries(all.map((k) => [k, 0]));
    if (s.status) row[s.status] = (row[s.status] ?? 0) + 1;
    byRfc.set(s.rfc, row);
  }
  const totals = Object.fromEntries(all.map((k) => [k, 0]));
  for (const row of byRfc.values()) for (const k of all) totals[k] += row[k];
  const header = ["RFC", ...all];
  const rows = [...byRfc.entries()]
    .sort()
    .map(([rfc, row]) => [rfc, ...all.map((k) => String(row[k]))]);
  rows.push(["TOTAL", ...all.map((k) => String(totals[k]))]);
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i].length)));
  const fmt = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(fmt(header));
  for (const r of rows) console.log(fmt(r));
}

function findStoryFile(id: string): string {
  const out = execSync(`find ${JSON.stringify(RFCS_DIR)} -path '*/stories/${id}.md' -print -quit`, {
    encoding: "utf8",
  }).trim();
  if (!out) {
    console.error(`error: story "${id}" not found under ${RFCS_DIR}`);
    process.exit(1);
  }
  return out;
}

function inGitRfcs(): void {
  if (!existsSync(join(RFCS_DIR, ".git"))) {
    console.error(
      `error: ${RFCS_DIR} is not a git repo. Clone blazetrailsdev/rfcs as a sibling of trails.`,
    );
    process.exit(1);
  }
}

function editFrontmatter(file: string, edits: Record<string, string>): void {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^(---\n)([\s\S]*?)(\n---\n)([\s\S]*)$/);
  if (!m) {
    console.error(`error: ${file} has no frontmatter block`);
    process.exit(1);
  }
  const lines = m[2].split("\n");
  for (const [key, value] of Object.entries(edits)) {
    let found = false;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith(`${key}:`)) {
        lines[i] = `${key}: ${value}`;
        found = true;
        break;
      }
    }
    if (!found) lines.push(`${key}: ${value}`);
  }
  writeFileSync(file, m[1] + lines.join("\n") + m[3] + m[4]);
}

function git(cmd: string, opts: { silent?: boolean } = {}): string {
  return execSync(`git -C ${JSON.stringify(RFCS_DIR)} ${cmd}`, {
    encoding: "utf8",
    stdio: opts.silent ? ["ignore", "pipe", "pipe"] : ["inherit", "pipe", "inherit"],
  }).trim();
}

function claim(id: string, assignee: string): void {
  inGitRfcs();
  git("pull --rebase --quiet origin main");
  const file = findStoryFile(id);
  const fm = readFileSync(file, "utf8");
  if (!/^claim: null\s*$/m.test(fm)) {
    console.error(`error: ${id} is already claimed`);
    process.exit(2);
  }
  const now = new Date().toISOString().replace(/\.\d+Z$/, "Z");
  editFrontmatter(file, {
    status: "claimed",
    claim: `"${now}"`,
    assignee: `"${assignee}"`,
  });
  git(`add ${JSON.stringify(file)}`);
  git(`commit -q -m ${JSON.stringify(`claim: ${id}`)}`);
  try {
    git("push --quiet origin main", { silent: true });
  } catch {
    git("reset --hard origin/main", { silent: true });
    console.error(`lost claim race on ${id} — pick another story`);
    process.exit(3);
  }
  console.log(`claimed ${id} as ${assignee}`);
}

function inProgress(id: string, pr: number): void {
  inGitRfcs();
  git("pull --rebase --quiet origin main");
  const file = findStoryFile(id);
  editFrontmatter(file, { status: "in-progress", pr: String(pr) });
  git(`add ${JSON.stringify(file)}`);
  git(`commit -q -m ${JSON.stringify(`in-progress: ${id} #${pr}`)}`);
  console.log(`marked ${id} in-progress #${pr} (push backgrounded)`);
}

function done(id: string, pr: number): void {
  inGitRfcs();
  git("pull --rebase --quiet origin main");
  const file = findStoryFile(id);
  editFrontmatter(file, { status: "done", pr: String(pr) });
  git(`add ${JSON.stringify(file)}`);
  git(`commit -q -m ${JSON.stringify(`done: ${id} #${pr}`)}`);
  console.log(`marked ${id} done #${pr} (push backgrounded)`);
}

function block(id: string, reason: string): void {
  inGitRfcs();
  git("pull --rebase --quiet origin main");
  const file = findStoryFile(id);
  editFrontmatter(file, { status: "blocked", "blocked-by": JSON.stringify(reason) });
  git(`add ${JSON.stringify(file)}`);
  git(`commit -q -m ${JSON.stringify(`block: ${id} — ${reason}`)}`);
  console.log(`blocked ${id}: ${reason} (push backgrounded)`);
}

function fmt(rows: StoryEntry[]): void {
  if (!rows.length) {
    console.log("(none)");
    return;
  }
  const cols = ["id", "rfc", "status", "cluster", "est_loc"] as const;
  const widths = cols.map((c) =>
    Math.max(c.length, ...rows.map((r) => String(r[c] ?? "—").length)),
  );
  const line = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(line([...cols]));
  for (const r of rows) console.log(line(cols.map((c) => String(r[c] ?? "—"))));
}

function parseFlags(args: string[]): { flags: Record<string, string | boolean>; rest: string[] } {
  const flags: Record<string, string | boolean> = {};
  const rest: string[] = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = args[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      rest.push(a);
    }
  }
  return { flags, rest };
}

function main(): void {
  const [cmd, ...rest] = process.argv.slice(2);
  const { flags, rest: pos } = parseFlags(rest);

  switch (cmd) {
    case "ready": {
      const index = loadIndex();
      const rows = ready(index, { rfc: flags.rfc as string | undefined });
      if (flags.json) console.log(JSON.stringify(rows, null, 2));
      else fmt(rows);
      break;
    }
    case "next-bundle": {
      const index = loadIndex();
      const maxLoc = Number(flags["max-loc"] ?? 250);
      const rows = nextBundle(index, {
        maxLoc,
        cluster: flags.cluster as string | undefined,
        rfc: flags.rfc as string | undefined,
      });
      if (flags.json) {
        const total = rows.reduce((a, b) => a + (b.est_loc ?? 0), 0);
        console.log(
          JSON.stringify({ stories: rows, bundle_total_loc: total, max_loc: maxLoc }, null, 2),
        );
      } else {
        const total = rows.reduce((a, b) => a + (b.est_loc ?? 0), 0);
        console.log(`bundle (sum ${total} / max ${maxLoc}):`);
        fmt(rows);
      }
      break;
    }
    case "list": {
      const index = loadIndex();
      const rows = listFiltered(index, {
        rfc: flags.rfc as string | undefined,
        status: flags.status as string | undefined,
        cluster: flags.cluster as string | undefined,
      });
      if (flags.json) console.log(JSON.stringify(rows, null, 2));
      else fmt(rows);
      break;
    }
    case "status": {
      statusCounts(loadIndex());
      break;
    }
    case "claim": {
      const id = pos[0];
      if (!id) usage();
      const assignee = (flags.assignee as string) ?? id;
      claim(id, assignee);
      break;
    }
    case "in-progress": {
      const id = pos[0];
      const pr = Number(flags.pr);
      if (!id || !pr) usage();
      inProgress(id, pr);
      break;
    }
    case "done": {
      const id = pos[0];
      const pr = Number(flags.pr);
      if (!id || !pr) usage();
      done(id, pr);
      break;
    }
    case "block": {
      const id = pos[0];
      const reason = (flags.reason as string) ?? pos[1];
      if (!id || !reason) usage();
      block(id, reason);
      break;
    }
    default:
      usage();
  }
}

function usage(): never {
  console.error(`usage: pnpm tasks <command>

  ready [--json] [--rfc <slug>]
  next-bundle [--max-loc N] [--cluster <name>] [--rfc <slug>] [--json]
  list [--rfc <slug>] [--status <v>] [--cluster <n>] [--json]
  status

  claim <id> [--assignee <name>]
  in-progress <id> --pr <N>
  done <id> --pr <N>
  block <id> --reason "<text>"

Set $RFCS_DIR to override the default ~/github/blazetrailsdev/rfcs.`);
  process.exit(2);
}

main();
