import { getFsAsync, getPathAsync } from "@blazetrails/activesupport";
import type { FsAdapter } from "@blazetrails/activesupport";
import ts from "typescript";

// A class is a model worth registering when its `extends` chain reaches the
// `Base` exported by `@blazetrails/activerecord`. We terminate the walk on a
// parent that is *that* import specifically — not any identifier named `Base`,
// so a class extending an unrelated `Base` from another package is not a model.
const AR_PACKAGE = "@blazetrails/activerecord";
const MANIFEST_NAME = "index.ts";

const HEADER =
  "// app/models/index.ts — AUTO-GENERATED by @blazetrails/activerecord-cli. Do not edit by hand.\n" +
  "// Re-run `ar generate:manifest` (or `ar init`) to update.\n";

/** A model class discovered by the scan, plus where to import it from. */
export interface ModelEntry {
  className: string; // the exported class name (also the imported binding name)
  importPath: string; // ESM specifier relative to the manifest, e.g. `./user.js`
  isDefault: boolean; // exported as `export default class` vs a named export
}

/**
 * What a class's `extends` target resolves to in its declaring file:
 * - `ar-base`: ActiveRecord's `Base` import → this class is a model root.
 * - `follow`: a local/relative name → keep walking via `byName`.
 * - `stop`: no superclass, or an external package import → not (by itself) a model.
 */
type ParentKind = "ar-base" | "follow" | "stop";

interface ClassDecl {
  name: string;
  parent: string | undefined; // the `extends` target's identifier name, if any
  parentKind: ParentKind;
  isDefault: boolean;
  isAbstract: boolean;
  file: string;
}

/** Source files we never treat as models: the manifest itself and tests. */
function isModelFile(file: string): boolean {
  return (
    file.endsWith(".ts") &&
    file !== MANIFEST_NAME &&
    !file.endsWith(".test.ts") &&
    !file.endsWith(".d.ts")
  );
}

function hasModifier(node: ts.ClassDeclaration, kind: ts.SyntaxKind): boolean {
  return (ts.getModifiers(node) ?? []).some((m) => m.kind === kind);
}

// `abstractClass` is the public getter/setter; `_abstractClass` is the backing
// field `Base` actually stores (base.ts) and several models set it directly
// (e.g. test-helpers/models/cat.ts). Accept either name.
const ABSTRACT_FLAGS = new Set(["abstractClass", "_abstractClass"]);

/** A class member that marks the class as abstract via `[_]abstractClass = true`. */
function memberMarksAbstract(m: ts.ClassElement): boolean {
  // `static [override] abstractClass = true;` (or `_abstractClass`)
  if (
    ts.isPropertyDeclaration(m) &&
    ts.isIdentifier(m.name) &&
    ABSTRACT_FLAGS.has(m.name.text) &&
    (m.modifiers ?? []).some((x) => x.kind === ts.SyntaxKind.StaticKeyword) &&
    m.initializer?.kind === ts.SyntaxKind.TrueKeyword
  ) {
    return true;
  }
  // `static { this.abstractClass = true; }` (or `this._abstractClass`) — the
  // dominant idiom in this repo's models, so detecting it is load-bearing.
  return (
    ts.isClassStaticBlockDeclaration(m) &&
    m.body.statements.some(
      (s) =>
        ts.isExpressionStatement(s) &&
        ts.isBinaryExpression(s.expression) &&
        s.expression.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        ts.isPropertyAccessExpression(s.expression.left) &&
        s.expression.left.expression.kind === ts.SyntaxKind.ThisKeyword &&
        ABSTRACT_FLAGS.has(s.expression.left.name.text) &&
        s.expression.right.kind === ts.SyntaxKind.TrueKeyword,
    )
  );
}

/**
 * Whether a class is an abstract base rather than a concrete model — the TS
 * `abstract` keyword, or the Rails-idiomatic `abstractClass = true` (as a
 * static field or a `static {}` block). These bridge the `extends` chain (so
 * their subclasses are found) but are never registered: they map to no table,
 * so registering one and reflecting its schema would fail.
 */
function isAbstractModel(node: ts.ClassDeclaration): boolean {
  if (hasModifier(node, ts.SyntaxKind.AbstractKeyword)) return true;
  return node.members.some(memberMarksAbstract);
}

interface FileImports {
  /** Locals bound to `@blazetrails/activerecord`'s `Base` (alias-aware). */
  arBase: Set<string>;
  /** Locals bound to any other non-relative (package) import. */
  external: Set<string>;
}

/**
 * Classify a file's imported identifiers so the inheritance walk can tell what
 * an `extends X` actually targets. `arBase` are bindings of ActiveRecord's
 * `Base` (`import { Base }` or `import { Base as AR }`). `external` are
 * bindings of any other package import — a parent resolving to one of these
 * must terminate the walk (it isn't a scanned local model), even if its name
 * collides with a real model/abstract base elsewhere in `app/models`. Relative
 * imports (`./x.js`) and same-file declarations are left out → followable.
 */
function collectImports(sf: ts.SourceFile): FileImports {
  const arBase = new Set<string>();
  const external = new Set<string>();
  for (const stmt of sf.statements) {
    if (!ts.isImportDeclaration(stmt) || !ts.isStringLiteral(stmt.moduleSpecifier)) continue;
    const spec = stmt.moduleSpecifier.text;
    const isRelative = spec.startsWith("./") || spec.startsWith("../");
    const clause = stmt.importClause;
    if (!clause) continue;
    const bind = (local: string, original: string): void => {
      if (spec === AR_PACKAGE && original === "Base") arBase.add(local);
      else if (!isRelative) external.add(local);
      // relative imports are followable, so they're intentionally untracked
    };
    if (clause.name) bind(clause.name.text, "default"); // `import Foo from ...`
    const nb = clause.namedBindings;
    if (nb && ts.isNamedImports(nb)) {
      for (const el of nb.elements) bind(el.name.text, (el.propertyName ?? el.name).text);
    } else if (nb && ts.isNamespaceImport(nb)) {
      bind(nb.name.text, "*"); // `import * as Foo from ...`
    }
  }
  return { arBase, external };
}

/** The identifier name of a class's `extends` clause, if it extends one. */
function extendsName(node: ts.ClassDeclaration): string | undefined {
  for (const clause of node.heritageClauses ?? []) {
    if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
    const expr = clause.types[0]?.expression;
    if (expr && ts.isIdentifier(expr)) return expr.text;
  }
  return undefined;
}

/**
 * Parse every model file under `modelsDir` and return the exported classes
 * whose `extends` chain transitively reaches `Base`, sorted by class name so
 * the emitted manifest is byte-stable.
 */
export async function scanModels(modelsDir: string): Promise<ModelEntry[]> {
  const fs = await getFsAsync();
  const path = await getPathAsync();

  let names: string[];
  try {
    names = await fs.readdir!(modelsDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error(`models directory not found: ${modelsDir}`, { cause: err });
    }
    throw err;
  }
  const files = names.filter(isModelFile).sort();

  const decls: ClassDecl[] = [];
  for (const file of files) {
    const text = await fs.readFile!(path.join(modelsDir, file), "utf8");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.ES2022, true);
    const imports = collectImports(sf);
    for (const stmt of sf.statements) {
      if (!ts.isClassDeclaration(stmt) || !stmt.name) continue;
      if (!hasModifier(stmt, ts.SyntaxKind.ExportKeyword)) continue;
      const parent = extendsName(stmt);
      let parentKind: ParentKind = "stop";
      if (parent !== undefined) {
        if (imports.arBase.has(parent)) parentKind = "ar-base";
        else if (imports.external.has(parent)) parentKind = "stop";
        else parentKind = "follow"; // same-file declaration or relative import
      }
      decls.push({
        name: stmt.name.text,
        parent,
        parentKind,
        isDefault: hasModifier(stmt, ts.SyntaxKind.DefaultKeyword),
        isAbstract: isAbstractModel(stmt),
        file,
      });
    }
  }
  // Two exported classes sharing a name collide on a single constant: the
  // manifest can't import both, and — keying `byName` below — a non-model
  // duplicate (`export class User {}`) would otherwise overwrite and silently
  // hide a real model of the same name. Reject the ambiguity outright.
  const byName = new Map<string, ClassDecl>();
  for (const d of decls) {
    const prior = byName.get(d.name);
    if (prior)
      throw new Error(`duplicate exported class "${d.name}" in ${prior.file} and ${d.file}`);
    byName.set(d.name, d);
  }

  // A class is a model iff its `extends` chain reaches ActiveRecord's `Base`.
  // `ar-base` terminates true; `follow` continues to the parent's local decl;
  // `stop` (no parent, or an external import) terminates false — so a parent
  // imported from another package never resolves to a same-named local model.
  // `seen` guards cyclic declarations, `cache` memoizes the single chain.
  const cache = new Map<string, boolean>();
  function reachesBase(name: string, seen: Set<string>): boolean {
    const cached = cache.get(name);
    if (cached !== undefined) return cached;
    const decl = byName.get(name);
    let result: boolean;
    if (!decl || decl.parentKind === "stop") result = false;
    else if (decl.parentKind === "ar-base") result = true;
    else if (!decl.parent || seen.has(name)) result = false;
    else {
      seen.add(name);
      result = reachesBase(decl.parent, seen);
    }
    cache.set(name, result);
    return result;
  }

  const models = decls.filter((d) => !d.isAbstract && reachesBase(d.name, new Set()));

  return models
    .map((d) => ({
      className: d.name,
      // `d.file` is a bare `*.ts` filename (isModelFile guarantees it); swap
      // the extension for the ESM `.js` specifier the manifest imports from.
      importPath: `./${d.file.replace(/\.ts$/, ".js")}`,
      isDefault: d.isDefault,
    }))
    .sort((a, b) => (a.className < b.className ? -1 : a.className > b.className ? 1 : 0));
}

/** Render the manifest source for a set of model entries. */
export function renderManifest(entries: ModelEntry[]): string {
  const names = entries.map((e) => e.className);
  let out = HEADER;
  out += `import { registerModel } from "@blazetrails/activerecord";\n`;
  for (const e of entries) {
    const binding = e.isDefault ? e.className : `{ ${e.className} }`;
    out += `import ${binding} from "${e.importPath}";\n`;
  }
  out += `\nexport const models = [${names.join(", ")}] as const;\n`;
  out += `for (const m of models) registerModel(m);\n`;
  if (names.length > 0) out += `\nexport { ${names.join(", ")} };\n`;
  return out;
}

/** Scan `modelsDir` and produce the manifest source it should contain. */
export async function buildManifest(modelsDir: string): Promise<string> {
  return renderManifest(await scanModels(modelsDir));
}

export interface ManifestResult {
  path: string; // absolute path of the manifest file
  content: string; // the manifest source the scan produced
  changed: boolean; // on-disk content differs (in write mode: was rewritten)
}

async function readIfPresent(fs: FsAdapter, path: string): Promise<string | undefined> {
  try {
    return await fs.readFile!(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

/**
 * Generate `<modelsDir>/index.ts`. With `check: true` it never writes — it only
 * reports whether the manifest is stale (CI drift detection). Otherwise it
 * writes only when content differs, keeping reruns idempotent.
 */
export async function generateManifest(
  modelsDir: string,
  options: { check?: boolean } = {},
): Promise<ManifestResult> {
  const fs = await getFsAsync();
  const path = (await getPathAsync()).join(modelsDir, MANIFEST_NAME);
  const content = await buildManifest(modelsDir);
  const existing = await readIfPresent(fs, path);
  const changed = existing !== content;
  if (!options.check && changed) await fs.writeFile!(path, content);
  return { path, content, changed };
}
