import { readdir, readFile, writeFile } from "fs/promises";
import { basename, join } from "path";
import ts from "typescript";

// A class is a model worth registering when its `extends` chain reaches
// `Base` (imported from `@blazetrails/activerecord`). Its declaration is never
// in the scanned files, so reaching the bare name `Base` terminates the walk.
const BASE_CLASS = "Base";
const MANIFEST_NAME = "index.ts";

const HEADER =
  "// models/index.ts — AUTO-GENERATED by @blazetrails/activerecord-cli. Do not edit by hand.\n" +
  "// Re-run `ar generate:manifest` (or `ar init`) to update.\n";

/** A model class discovered by the scan, plus where to import it from. */
export interface ModelEntry {
  className: string; // the exported class name (also the imported binding name)
  importPath: string; // ESM specifier relative to the manifest, e.g. `./user.js`
}

interface ClassDecl {
  name: string;
  parent: string | undefined; // the `extends` target's identifier name, if any
  file: string;
}

/** Source files we never treat as models: the manifest itself and tests. */
function isModelFile(file: string): boolean {
  return (
    file.endsWith(".ts") &&
    file !== MANIFEST_NAME &&
    !file.endsWith(".test.ts") &&
    !file.endsWith(".d.ts")
  );
}

function isExported(node: ts.ClassDeclaration): boolean {
  return (ts.getModifiers(node) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
}

/** The identifier name of a class's `extends` clause, if it extends one. */
function extendsName(node: ts.ClassDeclaration): string | undefined {
  for (const clause of node.heritageClauses ?? []) {
    if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
    const expr = clause.types[0]?.expression;
    if (expr && ts.isIdentifier(expr)) return expr.text;
  }
  return undefined;
}

/**
 * Parse every model file under `modelsDir` and return the exported classes
 * whose `extends` chain transitively reaches `Base`, sorted by class name so
 * the emitted manifest is byte-stable.
 */
export async function scanModels(modelsDir: string): Promise<ModelEntry[]> {
  const files = (await readdir(modelsDir)).filter(isModelFile).sort();

  const decls: ClassDecl[] = [];
  for (const file of files) {
    const text = await readFile(join(modelsDir, file), "utf8");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.ES2022, true);
    for (const stmt of sf.statements) {
      if (!ts.isClassDeclaration(stmt) || !stmt.name) continue;
      if (!isExported(stmt)) continue;
      decls.push({ name: stmt.name.text, parent: extendsName(stmt), file });
    }
  }
  const byName = new Map(decls.map((d) => [d.name, d]));

  // A class is a model iff its `extends` chain reaches `Base`; `seen` guards
  // cyclic declarations, `cache` memoizes shared ancestors.
  const cache = new Map<string, boolean>();
  function reachesBase(name: string, seen: Set<string>): boolean {
    if (name === BASE_CLASS) return true;
    const cached = cache.get(name);
    if (cached !== undefined) return cached;
    const decl = byName.get(name);
    if (!decl || !decl.parent || seen.has(name)) return false;
    seen.add(name);
    const result = reachesBase(decl.parent, seen);
    cache.set(name, result);
    return result;
  }

  return decls
    .filter((d) => d.parent !== undefined && reachesBase(d.name, new Set()))
    .map((d) => ({
      className: d.name,
      importPath: `./${basename(d.file, ".ts")}.js`,
    }))
    .sort((a, b) => (a.className < b.className ? -1 : a.className > b.className ? 1 : 0));
}

/** Render the manifest source for a set of model entries. */
export function renderManifest(entries: ModelEntry[]): string {
  const names = entries.map((e) => e.className);
  let out = HEADER;
  out += `import { registerModel } from "@blazetrails/activerecord";\n`;
  for (const e of entries) out += `import { ${e.className} } from "${e.importPath}";\n`;
  out += `\nexport const models = [${names.join(", ")}] as const;\n`;
  out += `for (const m of models) registerModel(m);\n`;
  if (names.length > 0) out += `\nexport { ${names.join(", ")} };\n`;
  return out;
}

/** Scan `modelsDir` and produce the manifest source it should contain. */
export async function buildManifest(modelsDir: string): Promise<string> {
  return renderManifest(await scanModels(modelsDir));
}

export interface ManifestResult {
  path: string; // absolute path of the manifest file
  content: string; // the manifest source the scan produced
  changed: boolean; // on-disk content differs (in write mode: was rewritten)
}

async function readIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

/**
 * Generate `<modelsDir>/index.ts`. With `check: true` it never writes — it only
 * reports whether the manifest is stale (CI drift detection). Otherwise it
 * writes only when content differs, keeping reruns idempotent.
 */
export async function generateManifest(
  modelsDir: string,
  options: { check?: boolean } = {},
): Promise<ManifestResult> {
  const path = join(modelsDir, MANIFEST_NAME);
  const content = await buildManifest(modelsDir);
  const existing = await readIfPresent(path);
  const changed = existing !== content;
  if (!options.check && changed) await writeFile(path, content, "utf8");
  return { path, content, changed };
}
